### ISSUE TITLE
Index error when running DCC

### ISSUE THREAD

**Issue by ShobanaSekar** [dieterich-lab/DCC#7] opened 2016-05-20 20:19 UTC
Hi,

I am getting this below error when running DCC. Could you help resolve this issue?

Traceback (most recent call last):
  File "/home/ssekar/tools/circRNA/DCC-0.3.2/DCC/main.py", line 507, in <module>
    main()
  File "/home/ssekar/tools/circRNA/DCC-0.3.2/DCC/main.py", line 292, in main
    filt.intersectLeftandRightRegions(nonrep_left,nonrep_right,indx0,count0)
  File "/home/ssekar/tools/circRNA/DCC-0.3.2/DCC/circFilter.py", line 119, in intersectLeftandRightRegions
    nonrep = np.concatenate((indx0[position],count0[position]),axis=1)
IndexError: axis 1 out of bounds [0, 1)

Thanks in advance,
Shobana

**Comment by tjakobi** [comment] 2016-05-31 15:30
Hi Shobana,

would it be possible to get a minimal sample data collection in order to reproduce this error?
Without the corresponding input data (and complete command line) it is hard to track down what the error caused.

Cheers,
Tobias

**Comment by ShobanaSekar** [comment] 2016-06-06 23:39
Hi,

Apologies for my late reply. Sure I can share the dataset. I have attached my out/error log here 
[DCC_Errorlog.txt](https://github.com/dieterich-lab/DCC/files/301546/DCC_Errorlog.txt)

I am getting this error: _**IndexError: list index out of range**_

Would this log file suffice or would you like the input fastqs as well? If so I can share it in dropbox to your email id.

Thanks,
Shobana

**Comment by hydraphenix** [comment] 2016-06-07 05:14
I met the error too.
And I un-installed the numpy package and re-install numpy1.9.2, then no bugs.
Maybe you can try it.

**Comment by tjakobi** [comment] 2016-06-07 06:57
Hi @hydraphenix,

thank you for your input, it is generally a good idea to keep packages updated, I did not notice any errors with newer numpy versions. 

@ShobanaS88: 
The error containted in the error messages should have been fixed recently. Please clone the current master branch and update your installation: "python setup.py install --force".

Cheers,
Tobias

**Comment by hydraphenix** [comment] 2016-06-07 08:20
@tjakobi 
Thank you for your reply and your advice.
Maybe I will do more test to check the real reason of the error report later. It may be caused by other reasons. I can run DCC now and thank you for your deverloping work.

**Comment by ShobanaSekar** [comment] 2016-06-09 17:07
Thank you @hydraphenix and @tjakobi for the suggestions. I was able to run DCC with the latest commit as you mentioned. Thank you once again!

Shobana

**Comment by tjakobi** [comment] 2016-06-09 17:15
Thanks for your feedback @ShobanaS88! I'll close the issue since the problem could be solved. In case of further problems, don't hesitate to open a new issue.

Cheers,
Tobias

**Closed as completed by tjakobi** 2016-06-09 17:15 UTC
