### ISSUE TITLE
temporary file problem

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/DCC#29] opened 2016-09-06 14:19 UTC
Traceback (most recent call last):
  File "/beegfs/homes/cdieterich/software/DCC/DCC_env/bin/DCC", line 11, in <module>
    load_entry_point('DCC==0.4.4', 'console_scripts', 'DCC')()
  File "build/bdist.linux-x86_64/egg/DCC/main.py", line 429, in main
  File "/biosw/python2/2.7.11/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/biosw/python2/2.7.11/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [Errno 2] No such file or directory: '/tmp/tmpQIwWxY'
srun: error: amalthea: task 0: Exited with exit code 1

**Comment by tjakobi** [comment] 2016-09-06 14:30
The -temp flag has been changed in the 0.4.4 release to -k. See the "Notes" section of the latest release:
https://github.com/dieterich-lab/DCC/releases/tag/v0.4.4

The use of the old flag now is read as "-t emp ", thus creating a folder "emp" as temporary directory which is probably not intended. 

Strangely, the error message refers to the system /tmp/ folder, which should not be used at all. I'll investigate this error.

**Comment by tjakobi** [comment] 2016-09-06 17:26
Tested with same CLI parameters and most recent build from GitHub (0.4.4 is 3 commits or so behind) and could not reproduce the error. Maybe fixed by one of the latest fixes (41d2fd17a6163df1ea22d277e2c82d5fa1d8f1a0)? Please try again with the latest stable GitHub version via git clone/pull.

**Closed as completed** 2016-09-29 14:49 UTC
Labels: bug
